In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)

3.0.5


In [2]:
url = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'

In [3]:
df = pd.read_csv(url)

In [4]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2


In [5]:
df.shape

(10000, 11)

In [6]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [7]:
df.fuel_type.nunique()

3

In [8]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [9]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [10]:
medianOLD = df['horsepower'].median()

In [11]:
aux = df['horsepower'].mode()[0]

In [12]:
horsepowerfill = df['horsepower'].fillna(aux)

In [13]:
medianNEW= horsepowerfill.median()

In [14]:
print(medianOLD, aux ,medianNEW)

254.0 252.0 252.0


In [15]:
df['origin'].value_counts()

origin
USA       4202
Asia      2994
Europe    2804
Name: count, dtype: int64

In [16]:
asia = df[df['origin'] == 'Asia']

In [17]:
X = asia[['vehicle_weight', 'model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [18]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [19]:
XTX_INVERT = np.linalg.inv(XTX)

In [20]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [21]:
w = XTX_INVERT @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [22]:
w.sum()

np.float64(0.36919696904927746)